### ISSUE TITLE
Add Cron-like format to list of valid Rocoto yaml schemas

### ISSUE THREAD

**Issue by uwagura** [ufs-community/uwtools#709]
**Description**
Rocoto allows you to specify cycle defs using a cron like format such as `0 0 1 1 1960-1962 * `, but the uwtools Rocoto yaml schema will reject such a format as invalid: 
```
[2025-03-15T17:53:51]    ERROR Error at workflow -> cycledef -> 0 -> spec:
[2025-03-15T17:53:51]    ERROR   '0 0 1 1 1960-1962 * ' is not valid under any of the given schemas
```
It would be nice if this format could be added to the list of allowed schemas!

**Requirements**
Simply accept cycledefs in cron like syntax

**Describe alternatives you've considered**
Iterating over years is technically possible using the current `YYYYMMDD` format, just a bit clunky

**Acceptance Criteria (Definition of Done)**
No UW schema-validation errors when using the above format

**Additional context**

**Comment by uwagura** [comment]
@maddenp-noaa I am using `uw version 2.5.1 build 0`.

**Comment by maddenp-noaa** [comment]
Thanks @uwagura. I have a potential fix, but could you please attach to this ticket your UW YAML file that is failing validation, or just the `workflow:` block that demonstrates the problem, or even just _some_ `workflow:` block that demonstrates a crontab-like spec you want to use that currently is rejected? I'd like to make sure the fix fixes your specific configuration. Thanks.

**Comment by uwagura** [comment]
@maddenp-noaa, sure, any yaml with a `spec` containing cron-like syntax has been failing for me. here is a minimal example
```
workflow:
    attrs:
        realtime: false
        scheduler: slurm

    cycledef:
        - attrs:
            group: faulty_yaml
          spec: "0 0 1 1 1960-1962 * " 

    log:
        cyclestr:
            value: /home/$USER/faulty.log

    tasks:
        task_generate_oce_atms:
            attrs:
               cycledefs: faulty_yaml
            command:
               cyclestr:
                  value: "echo \"test test 123\" "
            partition: batch
            jobname: generate_historical_atm_and_oce.sh
            nodes: 1:ppn=1
            walltime: 12:00:00

```

**Comment by maddenp-noaa** [comment]
Thanks. I tweaked the whitespace slightly, but then
`test.yaml`
```
workflow:
  attrs:
    realtime: false
    scheduler: slurm
  cycledef:
    - attrs:
        group: faulty_yaml
      spec: "0 0 1 1 1960-1962 *"
  log:
    cyclestr:
      value: /home/$USER/faulty.log
  tasks:
    task_generate_oce_atms:
      attrs:
        cycledefs: faulty_yaml
      command:
        cyclestr:
          value: "echo \"test test 123\" "
      partition: batch
      jobname: generate_historical_atm_and_oce.sh
      nodes: 1:ppn=1
      walltime: 12:00:00
```
yields
```
$ uw rocoto realize -c test.yaml -o test.xml
[2025-03-18T20:00:48]     INFO 0 schema-validation errors found in Rocoto config
[2025-03-18T20:00:48]     INFO 0 Rocoto XML validation errors found
```
`test.xml`
```
<?xml version='1.0' encoding='utf-8'?>
<workflow realtime="False" scheduler="slurm">
  <cycledef group="faulty_yaml">0 0 1 1 1960-1962 *</cycledef>
  <log>
    <cyclestr>/home/$USER/faulty.log</cyclestr>
  </log>
  <task name="generate_oce_atms" cycledefs="faulty_yaml">
    <nodes>1:ppn=1</nodes>
    <partition>batch</partition>
    <walltime>43200</walltime>
    <command>
      <cyclestr>echo "test test 123" </cyclestr>
    </command>
    <jobname>generate_historical_atm_and_oce.sh</jobname>
  </task>
</workflow>
```
Note that I removed the trailing space from inside the quoted `spec:` value, as the schema is not expecting trailing whitespace.

This looks good to me. Please let me know if you see any problems, but we'll start preparing a bugfix release. This issue may close, but we'll post a follow up comment when a new package is ready for you to test.
