### ISSUE TITLE
PBS pro job cards are not created correctly with UW drivers

### ISSUE THREAD

**Issue by mkavulich** [ufs-community/uwtools#726]
**Current Behavior**
When running with the attached example `config.yaml`, this is the resulting `runscript.mpas`:

```
$ uw mpas run --batch --config config.pbs_error.yaml --cycle 2022-05-01T00
...
...
$ cat /glade/work/kavulich/MPAS/test_rundir3/runscript.mpas
#!/bin/bash

#!/bin/bash

#PBS -A P48500053
#PBS -l select= 2:mpiprocs=12:ompthreads=1:ncpus=12
#PBS -l walltime= 01:30:00
#PBS -o runscript.mpas.out
#PBS -q main
#PBS rundir /glade/work/kavulich/MPAS/test_rundir4

time mpirun atmosphere_model
test $? -eq 0 && touch runscript.mpas.done
```
These #PBS directives are malformed (spaces are not allowed). Attempting to submit this batch script gives the following error:

`qsub: directive error: -l select= 2:mpiprocs=12:ompthreads=1:ncpus=12`

Removing the spaces gives another error because there is no "rundir" directive in PBS pro:

`qsub: directive error: rundir /glade/work/kavulich/MPAS/test_rundir4`

**Expected Behavior**

The MPAS driver should be able to create a valid PBS pro job card to run an MPAS experiment

**To Reproduce**

See above, running on Derecho with the following config.yaml:

```
mpas:
  domain: regional
  execution:
    batchargs:
      tasks_per_node: 12
      nodes: 2
      walltime: "01:30:00"
      queue: main
    executable: atmosphere_model
    mpicmd: mpirun
  files_to_copy:
    atmosphere_model: /glade/campaign/ral/jntp/mayfield/dtc_ncar_mpas/MPAS-Model/atmosphere_model
    conus.graph.info: "{{ user.grid_info_dir }}/conus_15km.graph.info.part.12"
    init.nc: "{{ user.expts_base_dir }}/mpas_init/2022050100/ens_1/init.nc"
    stream_list.atmosphere.diagnostics: "{{ user.mpas_model_dir }}/stream_list.atmosphere.diagnostics"
    stream_list.atmosphere.output: "{{ user.mpas_model_dir }}/stream_list.atmosphere.output"
    stream_list.atmosphere.surface: "{{ user.mpas_model_dir }}/stream_list.atmosphere.surface"
  lateral_boundary_conditions:
    interval_hours: 6
    offset: 0
    path: "{{ user.expts_base_dir }}/mpas_init/2022050100/ens_1/"
  length: 6
  namelist:
    base_file: "{{ user.mpas_model_dir }}/namelist.atmosphere"
    validate: true
  rundir: /glade/work/kavulich/MPAS/test_rundir4
  streams:
    input:
      filename_template: init.nc
      input_interval: initial_only
      mutable: false
      type: input
    output:
      clobber_mode: overwrite
      filename_template: history.$Y-$M-$D_$h.$m.$s.nc
      io_type: pnetcdf
      mutable: true
      output_interval: "6:00:00"
      reference_time: "2022-05-01 00:00:00"
      type: output
platform:
  account: P48500053
  scheduler: pbs
user:
  expts_base_dir: /glade/campaign/ral/jntp/mayfield/dtc_ncar_mpas/expts_dir/test_regional_stoch/conus_15km_ensemble/
  grid_info_dir: /glade/campaign/ral/jntp/mayfield/dtc_ncar_mpas/meshes/
  mpas_model_dir: /glade/campaign/ral/jntp/mayfield/dtc_ncar_mpas/MPAS-Model/

```

**Additional Context**

Let me know if there's any more information I can provide

**Current Version**

uw version 2.6.2 build 0
